/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#include "button_handler.h"
#include "board_init.h"
#include "menu.h"
#include "space.h"
#include "snake.h"
#include <stdio.h>

// Track previous button states to detect press/release
static bool button_a_prev_state = false;
static bool button_b_prev_state = false;

// Button A callback - central router
void button_a_callback(void)
{
    bool current_state = BUTTON_A_IS_PRESSED;
    bool is_pressed = current_state && !button_a_prev_state;  // Rising edge
    bool is_released = !current_state && button_a_prev_state; // Falling edge
    button_a_prev_state = current_state;
    
    bool menu_active = menu_is_active();
    SpaceState space_state = space_get_state();
    SnakeState snake_state = snake_get_state();
    
    if (is_pressed)
    {
        printf("[BTN A] PRESSED - Menu=%d, Space=%d, Snake=%d\r\n", menu_active, space_state, snake_state);
        
        // Priority 1: Snake game playing
        if (snake_state == SNAKE_STATE_PLAYING)
        {
            printf("[BTN A] -> Snake TURN LEFT\r\n");
            snake_button_left_pressed();
        }
        // Priority 2: Space Invaders game playing
        else if (space_state == SPACE_STATE_PLAYING)
        {
            printf("[BTN A] -> Space LEFT\r\n");
            space_button_left_pressed();
        }
        // Priority 2: Menu navigation
        else if (menu_active)
        {
            printf("[BTN A] -> Menu Next\r\n");
            menu_handle_button_a();
        }
        // Priority 3: Game over
        else if (space_state == SPACE_STATE_OVER)
        {
            printf("[BTN A] -> Return to menu\r\n");
            menu_set_active(true);
        }
    }
    else if (is_released)
    {
        printf("[BTN A] RELEASED\r\n");
        // Button released
        if (space_state == SPACE_STATE_PLAYING)
        {
            space_button_left_released();
        }
    }
}

// Button B callback - central router
void button_b_callback(void)
{
    bool current_state = BUTTON_B_IS_PRESSED;
    bool is_pressed = current_state && !button_b_prev_state;  // Rising edge
    bool is_released = !current_state && button_b_prev_state; // Falling edge
    button_b_prev_state = current_state;
    
    bool menu_active = menu_is_active();
    SpaceState space_state = space_get_state();
    SnakeState snake_state = snake_get_state();
    
    if (is_pressed)
    {
        printf("[BTN B] PRESSED - Menu=%d, Space=%d, Snake=%d\r\n", menu_active, space_state, snake_state);
        
        // Priority 1: Snake game playing
        if (snake_state == SNAKE_STATE_PLAYING)
        {
            printf("[BTN B] -> Snake TURN RIGHT\r\n");
            snake_button_right_pressed();
        }
        // Priority 2: Space Invaders game playing
        else if (space_state == SPACE_STATE_PLAYING)
        {
            printf("[BTN B] -> Space RIGHT\r\n");
            space_button_right_pressed();
        }
        // Priority 2: Menu selection
        else if (menu_active)
        {
            printf("[BTN B] -> Menu Select\r\n");
            menu_handle_button_b();
        }
        // Priority 3: Game over
        else if (space_state == SPACE_STATE_OVER)
        {
            printf("[BTN B] -> Return to menu\r\n");
            menu_set_active(true);
        }
    }
    else if (is_released)
    {
        printf("[BTN B] RELEASED\r\n");
        // Button released
        if (space_state == SPACE_STATE_PLAYING)
        {
            space_button_right_released();
        }
    }
}

// Reset button callback
void button_reset_callback(void)
{
    printf("[BTN RESET] Pressed\r\n");
    
    SpaceState space_state = space_get_state();
    
    // Check if we're in-game
    if (space_state == SPACE_STATE_PLAYING)
    {
        printf("[BTN RESET] -> Fire bullet\r\n");
        space_fire_bullet();
    }
    else if (space_state == SPACE_STATE_OVER)
    {
        printf("[BTN RESET] -> Restart game\r\n");
        space_reset();
    }
}
