/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _BUTTON_HANDLER_H
#define _BUTTON_HANDLER_H

// Central button event handler
// Routes button events to the appropriate module (menu, game, etc.)

void button_a_callback(void);
void button_b_callback(void);
void button_reset_callback(void);

#endif // _BUTTON_HANDLER_H
