/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _FOSGAME_H
#define _FOSGAME_H

#include <stdint.h>
#include <stdbool.h>

// Lottery prize types
typedef enum {
    PRIZE_LOSE,
    PRIZE_TSHIRT,
    PRIZE_CAP,
    PRIZE_COOKIES,
    PRIZE_GPS_TRACKER,
    PRIZE_BEANIES,
    PRIZE_BASECAPS,
    PRIZE_LUGGAGE_TAG,
    PRIZE_BOTTLE_OPENER,
    PRIZE_PENS
} PrizeType;

// Initialize and run FOSGAME lottery
void fosgame_run(void);

// Get random prize
PrizeType fosgame_get_prize(void);

#endif // _FOSGAME_H
