/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _MENU_H
#define _MENU_H

#include <stdint.h>
#include <stdbool.h>

// Menu item types
typedef enum {
    MENU_ITEM_SPACE,        // Space Invaders game
    MENU_ITEM_SNAKE,        // Snake game
    MENU_ITEM_SLOTMACHINE,  // Slot Machine game
    MENU_ITEM_FOSGAME,      // FOSGAME lottery
    MENU_ITEM_ECLIPSE,      // Show Eclipse Foundation logo
    MENU_ITEM_COUNT         // Total number of menu items
} MenuItem;

// Menu state management
void menu_init(void);
void menu_display(void);
void menu_navigate_next(void);
void menu_select_item(void);
bool menu_is_active(void);
void menu_set_active(bool active);

// Button event handlers for menu
void menu_handle_button_a(void);
void menu_handle_button_b(void);

#endif // _MENU_H
