/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _SCREEN_H
#define _SCREEN_H

/* Enumration for line on the screen */
typedef enum
{
    L0 = 0,
    L1 = 18,
    L2 = 36,
    L3 = 54
} LINE_NUM;

void screen_print(char* str, LINE_NUM line);
void screen_printn(const char* str, unsigned int str_length, LINE_NUM line);
void screen_draw_smiley(void);
void screen_draw_smiley_happy(void);
void screen_draw_smiley_neutral(void);
void screen_draw_smiley_sad(void);

#endif // _SCREEN_H