/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _SLOTMACHINE_H
#define _SLOTMACHINE_H

#include <stdint.h>
#include <stdbool.h>

// Slot symbols (Mario theme)
typedef enum {
    SYMBOL_STAR,      // ★ Star
    SYMBOL_MUSHROOM,  // ◆ Mushroom
    SYMBOL_FLOWER,    // ❀ Flower
    SYMBOL_COUNT      // Total number of symbols
} SlotSymbol;

// Run slot machine game
void slotmachine_run(void);

#endif // _SLOTMACHINE_H
