/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _SNAKE_H
#define _SNAKE_H

#include <stdint.h>
#include <stdbool.h>

// Game state
typedef enum {
    SNAKE_STATE_PLAYING,
    SNAKE_STATE_OVER
} SnakeState;

// Direction
typedef enum {
    DIRECTION_UP,
    DIRECTION_RIGHT,
    DIRECTION_DOWN,
    DIRECTION_LEFT
} Direction;

// Snake segment
typedef struct {
    int x;
    int y;
} SnakeSegment;

// Initialize and run the snake game
void snake_game(void);

// Game state management
SnakeState snake_get_state(void);
void snake_set_state(SnakeState state);
void snake_reset(void);

// Button handlers
void snake_button_left_pressed(void);
void snake_button_right_pressed(void);

#endif // _SNAKE_H
