/* 
 * Copyright (c) 2026 Eclipse Foundation
 * 
 *  This program and the accompanying materials are made available 
 *  under the terms of the MIT license which is available at
 *  https://opensource.org/license/mit.
 * 
 *  SPDX-License-Identifier: MIT
 * 
 *  Contributors: 
 *     Sébastien Heurtematte - 2026 version.
 * 
 * 
 * // Some portions generated by Co-Pilot
 */

#ifndef _SPACE_H
#define _SPACE_H

#include <stdint.h>
#include <stdbool.h>

// Space Invaders game state
typedef enum {
    SPACE_STATE_MENU,      // Showing smiley menu
    SPACE_STATE_PLAYING,   // In-game
    SPACE_STATE_OVER       // Game over screen
} SpaceState;

// Get current game state
SpaceState space_get_state(void);

// Set game state
void space_set_state(SpaceState state);

// Game control functions
void space_move_left(void);
void space_move_right(void);

void space_button_left_pressed(void);
void space_button_left_released(void);
void space_button_right_pressed(void);
void space_button_right_released(void);
void space_fire_bullet(void);
void space_reset(void);

// Main game loop
void space_invaders_game(void);

#endif // _SPACE_H
